DevSpot/Models/JobPosting.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace DevSpot.Models
{
    public class JobPosting
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Company { get; set; }

        [Required]
        public string Location { get; set; }

        public DateTime PostedDate { get; set; } = DateTime.UtcNow;

        public bool IsApproved { get; set; }

        [Required]
        public string UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        public IdentityUser User { get; set; }
    }
}

DevSpot/ViewModels/JobPostingViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DevSpot.ViewModels
{
	public class JobPostingViewModel
	{
		[Required]
		public string Title { get; set; }

		[Required]
		public string Description { get; set; }

		[Required]
		public string Company { get; set; }

		[Required]
		public string Location { get; set; }
	}
}

DevSpot/Controllers/JobPostingsController.cs
using DevSpot.Constants;
using DevSpot.Models;
using DevSpot.Repositories;
using DevSpot.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DevSpot.Controllers
{
	[Authorize]
	public class JobPostingsController : Controller
	{
		private readonly IRepository<JobPosting> _repository;
		private readonly UserManager<IdentityUser> _userManager;

		public JobPostingsController(
			IRepository<JobPosting> repository,
			UserManager<IdentityUser> userManager)
		{
			_repository = repository;
			_userManager = userManager;
		}

		[AllowAnonymous]
		public async Task<IActionResult> Index()
		{
			var jobPostings = await _repository.GetAllAsync();

			if (User.IsInRole(Roles.EMPLOYER))
			{
				var userId = _userManager.GetUserId(User);
				jobPostings = jobPostings.Where(jp => jp.UserId == userId);
			}

			return View(jobPostings);
		}

		[Authorize(Roles = "Admin, Employer")]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[Authorize(Roles = "Admin, Employer")]
		public async Task<IActionResult> Create(JobPostingViewModel jobPostingVM)
		{
			if(ModelState.IsValid)
			{
				var jobPosting = new JobPosting
				{
					Title = jobPostingVM.Title,
					Description = jobPostingVM.Description,
					Company = jobPostingVM.Company,
					Location = jobPostingVM.Location,
					UserId = _userManager.GetUserId(User)
				};

				await _repository.AddAsync(jobPosting);

				return RedirectToAction(nameof(Index));
			}

			return View(jobPostingVM);
		}

		[HttpDelete]
		[Authorize(Roles = "Admin, Employer")]
		public async Task<IActionResult> Delete(int id)
		{
			var jobPosting = await _repository.GetByIdAsync(id);
			if (jobPosting == null) 
			{
				return NotFound();
			}

			var userId = _userManager.GetUserId(User);

			if(User.IsInRole(Roles.ADMIN) == false && jobPosting.UserId != userId)
			{
				return Forbid();
			}

			await _repository.DeleteAsync(id);

			return Ok();
		}

		[Authorize(Roles = "Admin, Employer")]
		public async Task<IActionResult> DeleteEasy(int id)
		{
			var jobPosting = await _repository.GetByIdAsync(id);
			if (jobPosting == null)
			{
				return NotFound();
			}

			var userId = _userManager.GetUserId(User);

			if (User.IsInRole(Roles.ADMIN) == false && jobPosting.UserId != userId)
			{
				return Forbid();
			}

			await _repository.DeleteAsync(id);

			return RedirectToAction("Index");
		}
	}
}

DevSpot/Views/JobPostings/Create.cshtml
@model DevSpot.ViewModels.JobPostingViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Create</h1>

<form method="post" action="Create">
    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input type="text" asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <textarea type="text" asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Company" class="form-label"></label>
        <input type="text" asp-for="Company" class="form-control" />
        <span asp-validation-for="Company" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Location" class="form-label"></label>
        <input type="text" asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DevSpot/Views/JobPostings/Index.cshtml
@using DevSpot.Constants;
@model IEnumerable<JobPosting>

@{
}

<h1 class="text-center m-5">All Developer Jobs</h1>

<div class="list-group">

    @foreach (var jobPosting in Model)
    {
        <div class="list-group-item" id="job-posting-@jobPosting.Id">
            <h3>@jobPosting.Title</h3>
            <p>@jobPosting.Description</p>
            <p><strong>Company:</strong> @jobPosting.Company</p>
            <p><strong>Location:</strong> @jobPosting.Location</p>
            <p><strong>Posted on:</strong> @jobPosting.PostedDate.ToShortDateString()</p>

            @if (User.IsInRole(Roles.ADMIN) || User.IsInRole(Roles.EMPLOYER))
            {
                <div>
                    <button onclick="deleteJobPosting(@jobPosting.Id)" class="btn btm-sm btn-danger">Delete</button>
                </div>

                <a asp-action="DeleteEasy" asp-route-id="@jobPosting.Id">Delete</a>
            }

        </div>
    }

</div>

@section Scripts {
    <script>
        function deleteJobPosting(id) {
            if (confirm("Are you sure you want to delete this job posting?")) {

                // url
                // type (delete)
                // succes => visually remove the job posting list item
                // fail => show error message

                $.ajax({
                    url: "@Url.Action("Delete", "JobPostings")/" + id, // .../jobpostings/delete/3
                    type: "delete",
                    success: function(result) {
                        $("#job-posting-" + id).remove();
                    },
                    error: function(err) {
                        alert("An error occured");
                    }
                });
            }
        }
    </script>
}